[package]
name = "xtcp"
version = "0.1.0"
authors = ["jfecher", "ryandrew"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.116"
serde_json = { version="1.0.57", features=["arbitrary_precision"] }
